import { defineType, defineField } from "sanity";

export default defineType({
  name: "investmentPage",
  title: "Investment Page",
  type: "document",
  fields: [
    defineField({ name: "seo", title: "SEO", type: "seoObject" }),
    defineField({
      name: "heroTagline",
      title: "Hero Tagline (overline)",
      type: "string",
      initialValue: "Investment Grade",
    }),
    defineField({
      name: "heroHeading",
      title: "Hero Heading",
      type: "string",
      initialValue: "Diamonds as a Portable, Stateless Asset.",
    }),
    defineField({
      name: "heroSubtext",
      title: "Hero Subtext",
      type: "text",
      rows: 3,
      initialValue: "Natural FL diamonds represent the apex of the GIA grading scale. We work with serious buyers — private individuals and institutional — seeking certifiable hard assets outside the share market.",
    }),
    defineField({
      name: "heroCta",
      title: "Hero CTA Label",
      type: "string",
      initialValue: "Book a Consultation",
    }),
    defineField({
      name: "heroSecondaryCta",
      title: "Hero Secondary CTA Label",
      type: "string",
      initialValue: "Browse IF→FL Inventory",
    }),
    defineField({
      name: "heroImage",
      title: "Hero Image",
      type: "image",
      options: { hotspot: true },
    }),
    defineField({
      name: "assetClassTagline",
      title: "Asset Class Section Tagline",
      type: "string",
      initialValue: "The Case for Diamonds",
    }),
    defineField({
      name: "assetClassHeading",
      title: "Asset Class Section Heading",
      type: "string",
      initialValue: "Why natural FL diamonds hold value.",
    }),
    defineField({
      name: "assetClassPoints",
      title: "Asset Class Points",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "title", type: "string", title: "Title" },
          { name: "body", type: "text", title: "Body", rows: 3 },
          { name: "tag", type: "string", title: "Tag/Badge" },
        ],
        preview: { select: { title: "title" } },
      }],
      initialValue: [
        { title: "Wealth Preservation", body: "Natural FL diamonds in D–F colour have held and appreciated in AUD terms over 10-year periods. No counterparty risk. No custodian required.", tag: "Hard asset" },
        { title: "Rarity Premium", body: "FL and IF in D–F colour represent less than 1% of all GIA-graded stones globally. Supply cannot be manufactured on demand.", tag: "Top 1%" },
        { title: "Value Transparency", body: "Every stone has a GIA certificate with a unique number, publicly verifiable. The IF→FL uplift creates a new, independent certificate — the value created is documented and auditable.", tag: "GIA verifiable" },
      ],
    }),
    defineField({
      name: "rarityTagline",
      title: "Rarity Section Tagline",
      type: "string",
      initialValue: "The GIA Scale",
    }),
    defineField({
      name: "rarityHeading",
      title: "Rarity Section Heading",
      type: "string",
      initialValue: "The Apex of Rarity: GIA Flawless.",
    }),
    defineField({
      name: "rarityBody",
      title: "Rarity Section Body",
      type: "text",
      rows: 4,
      initialValue: "The GIA Flawless grade means no internal or external characteristics are visible under 10× magnification to a skilled grader. It is the pinnacle of clarity — and the destination of our IF→FL conversion work.",
    }),
    defineField({
      name: "conversionTagline",
      title: "Conversion Process Tagline",
      type: "string",
      initialValue: "The Uplift Process",
    }),
    defineField({
      name: "conversionHeading",
      title: "Conversion Process Heading",
      type: "string",
      initialValue: "Six Steps from IF to Flawless.",
    }),
    defineField({
      name: "conversionSteps",
      title: "Conversion Process Steps",
      type: "array",
      of: [{
        type: "object",
        fields: [
          { name: "step", type: "string", title: "Step Number (e.g. 01)" },
          { name: "label", type: "string", title: "Step Label" },
          { name: "body", type: "text", title: "Step Description", rows: 3 },
        ],
        preview: { select: { title: "label", subtitle: "step" } },
      }],
    }),
    defineField({
      name: "profitSplitHeading",
      title: "50/50 Profit Split Heading",
      type: "string",
      initialValue: "We only earn when you earn — 50/50 profit split.",
    }),
    defineField({
      name: "profitSplitBody",
      title: "50/50 Profit Split Body",
      type: "text",
      rows: 3,
      initialValue: "No upfront cost. No conversion fee. We calculate the IF value, the projected FL value, document it in writing, then share the profit we create together.",
    }),
    defineField({
      name: "ctaHeading",
      title: "Consultation CTA Heading",
      type: "string",
      initialValue: "Ready to explore your stone's potential?",
    }),
    defineField({
      name: "ctaBody",
      title: "Consultation CTA Body",
      type: "text",
      rows: 2,
      initialValue: "Whether you hold an IF stone or are looking to acquire an FL-grade asset, start with a conversation. No obligation, no salesmanship.",
    }),
  ],
  preview: { prepare: () => ({ title: "Investment Page" }) },
});
